// Локалізовані лейбли для filter + table keys (M1.3e).

export const FILTER_LABELS: Record<string, string> = {
  search: "Пошук",
  statusGeneralId: "Статус",
  statusOperationalId: "Оперативний статус",
  searchChannelId: "Канал пошуку",
  deliveryMethodId: "Спосіб доставки",
  categoryTTId: "Категорія ТТ",
  priceTypeId: "Тип цін",
  primaryAssortmentId: "Асортимент",
  primaryRouteId: "Маршрут",
  agentUserId: "Агент",
  region: "Область",
  city: "Місто",
  daysSinceRange: "Днів без покупки",
  createdRange: "Створений (період)",
  hasDebt: "Є борг",
  hasOverpayment: "Є переплата",
  onlyMine: "Тільки мої",
  hideTrash: "Прибрати приховані",
};

export const COLUMN_LABELS: Record<string, string> = {
  name: "Найменування",
  tradePointName: "Назва ТТ",
  code1C: "Код 1С",
  phonePrimary: "Телефон",
  statusGeneral: "Статус",
  statusOperational: "Оперативний статус",
  searchChannel: "Канал пошуку",
  deliveryMethod: "Спосіб доставки",
  categoryTT: "Категорія ТТ",
  priceType: "Тип цін",
  primaryAssortment: "Асортимент",
  primaryRoute: "Маршрут",
  agent: "Агент",
  region: "Область",
  city: "Місто",
  debt: "Борг",
  overdueDebt: "Просрочений борг",
  monthlyVolume: "Об'єм/міс",
  daysSinceLast: "Днів без покупки",
  lastSyncedAt: "Оновлено",
  createdAt: "Створений",
};
